FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App
COPY . ./
RUN dotnet restore ./src/HAN.ICDETool.Web/HAN.ICDETool.Web.csproj
RUN dotnet publish ./src/HAN.ICDETool.Web/HAN.ICDETool.Web.csproj -c Release -o out

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build-env /app/out/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf