FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App
COPY . ./
RUN dotnet restore ./src/HAN.ICDETool.Api/HAN.ICDETool.Api.csproj
RUN dotnet publish ./src/HAN.ICDETool.Api/HAN.ICDETool.Api.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "HAN.ICDETool.Api.dll"]