// <auto-generated />
using System;
using HAN.ICDETool.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAN.ICDETool.Infrastructure.Migrations
{
    [DbContext(typeof(ICDEContext))]
    [Migration("20221214195420_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Huisnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocatieId")
                        .HasColumnType("int");

                    b.Property<string>("Plaatsnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toevoeging")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocatieId")
                        .IsUnique();

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Beoordeling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TentamenUitvoeringId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TentamenUitvoeringId");

                    b.ToTable("Beoordeling");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.BeoordelingsCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubricId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("BeoordelingsCriteria");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.BeroepsProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.Property<int>("TeBehalenStudiepunten")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.ToTable("BeroepsProduct");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseInrichting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefintief")
                        .HasColumnType("bit");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDatum")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.ToTable("CourseUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekInrichting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseWeekPlanningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseWeekPlanningId");

                    b.ToTable("CourseWeekInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId")
                        .IsUnique();

                    b.ToTable("CourseWeekPlanning");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseUitvoeringId")
                        .HasColumnType("int");

                    b.Property<int>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseUitvoeringId");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.ToTable("CourseWeekUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.EenheidVanLeeruitkomsten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.ToTable("EenheidVanLeeruitkomsten");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Klas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Klas");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Leerdoel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeeruitkomstId")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeeruitkomstId");

                    b.ToTable("Leerdoel");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Leeruitkomst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EenheidVanLeeruitkomstenId")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EenheidVanLeeruitkomstenId");

                    b.ToTable("Leeruitkomst");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesInrichting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.Property<int>("LeerdoelId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.HasIndex("LeerdoelId");

                    b.ToTable("LesInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesMateriaal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LesInrichtingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LesInrichtingId");

                    b.ToTable("LesMateriaal");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesMateriaalLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LesMateriaalId")
                        .HasColumnType("int");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LesMateriaalId");

                    b.ToTable("LesMateriaalLine");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseWeekUitvoeringId")
                        .HasColumnType("int");

                    b.Property<int?>("DocentId")
                        .HasColumnType("int");

                    b.Property<int?>("LocatieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseWeekUitvoeringId");

                    b.HasIndex("DocentId");

                    b.HasIndex("LocatieId");

                    b.ToTable("LesUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Locatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocatieType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locatie");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Opleiding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Opleiding");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.OpleidingsProfiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpleidingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpleidingId");

                    b.ToTable("OpleidingsProfiel");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Rubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeroepsProductId")
                        .HasColumnType("int");

                    b.Property<int>("KnockoutThreshold")
                        .HasColumnType("int");

                    b.Property<int>("LeerdoelId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoldoendeThreshold")
                        .HasColumnType("int");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeroepsProductId");

                    b.HasIndex("LeerdoelId");

                    b.ToTable("Rubric");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.SchriftelijkeToets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.Property<int>("LeerdoelId")
                        .HasColumnType("int");

                    b.Property<int>("TeBehalenStudiepunten")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.HasIndex("LeerdoelId");

                    b.ToTable("SchriftelijkeToets");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.TentamenUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeroepsProductId")
                        .HasColumnType("int");

                    b.Property<int>("CourseUitvoeringId")
                        .HasColumnType("int");

                    b.Property<int>("CourseWeekUitvoeringId")
                        .HasColumnType("int");

                    b.Property<int?>("DocentId")
                        .HasColumnType("int");

                    b.Property<int?>("LocatieId")
                        .HasColumnType("int");

                    b.Property<int?>("SchriftelijkeToetsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeroepsProductId");

                    b.HasIndex("CourseWeekUitvoeringId");

                    b.HasIndex("DocentId");

                    b.HasIndex("LocatieId");

                    b.HasIndex("SchriftelijkeToetsId");

                    b.ToTable("TentamenUitvoering");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser<int>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Persoon", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<int>");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MentorVanKlasId")
                        .HasColumnType("int");

                    b.Property<int?>("VolgtCourseId")
                        .HasColumnType("int");

                    b.Property<int?>("VolgtProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZitInKlasId")
                        .HasColumnType("int");

                    b.HasIndex("MentorVanKlasId")
                        .IsUnique()
                        .HasFilter("[MentorVanKlasId] IS NOT NULL");

                    b.HasIndex("VolgtCourseId");

                    b.HasIndex("VolgtProfileId");

                    b.HasIndex("ZitInKlasId");

                    b.HasDiscriminator().HasValue("Persoon");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Adres", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.Locatie", null)
                        .WithOne("Adres")
                        .HasForeignKey("HAN.ICDETool.Core.Entities.Adres", "LocatieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Beoordeling", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.Persoon", "Docent")
                        .WithMany("BeoordelingenGegeven")
                        .HasForeignKey("DocentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.Persoon", "Student")
                        .WithMany("BeoordelingenOntvangen")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.TentamenUitvoering", "TentamenUitvoering")
                        .WithMany("Beoordelingen")
                        .HasForeignKey("TentamenUitvoeringId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Docent");

                    b.Navigation("Student");

                    b.Navigation("TentamenUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.BeoordelingsCriteria", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.Rubric", null)
                        .WithMany("BeoordelingsCriteria")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.BeroepsProduct", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseInrichting", null)
                        .WithMany("BeroepsProducten")
                        .HasForeignKey("CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekInrichting", null)
                        .WithMany("BeroepsProduct")
                        .HasForeignKey("CourseWeekInrichtingId");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseInrichting", "CourseInrichting")
                        .WithMany("CourseUitvoeringen")
                        .HasForeignKey("CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekInrichting", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekPlanning", null)
                        .WithMany("Weken")
                        .HasForeignKey("CourseWeekPlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekPlanning", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseInrichting", null)
                        .WithOne("Planning")
                        .HasForeignKey("HAN.ICDETool.Core.Entities.CourseWeekPlanning", "CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseUitvoering", null)
                        .WithMany("Weken")
                        .HasForeignKey("CourseUitvoeringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekInrichting", "CourseWeekInrichting")
                        .WithMany("CourseWeekUitvoeringen")
                        .HasForeignKey("CourseWeekInrichtingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseWeekInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.EenheidVanLeeruitkomsten", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseInrichting", null)
                        .WithMany("Evls")
                        .HasForeignKey("CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Leerdoel", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.Leeruitkomst", null)
                        .WithMany("Leerdoelen")
                        .HasForeignKey("LeeruitkomstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Leeruitkomst", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.EenheidVanLeeruitkomsten", null)
                        .WithMany("Leeruitkomsten")
                        .HasForeignKey("EenheidVanLeeruitkomstenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesInrichting", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseInrichting", null)
                        .WithMany("Lessen")
                        .HasForeignKey("CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekInrichting", null)
                        .WithMany("Lessen")
                        .HasForeignKey("CourseWeekInrichtingId");

                    b.HasOne("HAN.ICDETool.Core.Entities.Leerdoel", "Leerdoel")
                        .WithMany("GekoppeldeLessen")
                        .HasForeignKey("LeerdoelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Leerdoel");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesMateriaal", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.LesInrichting", null)
                        .WithMany("LesMateriaal")
                        .HasForeignKey("LesInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesMateriaalLine", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.LesMateriaal", null)
                        .WithMany("Inhoud")
                        .HasForeignKey("LesMateriaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekUitvoering", "CourseWeekUitvoering")
                        .WithMany("Lessen")
                        .HasForeignKey("CourseWeekUitvoeringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.Persoon", "Docent")
                        .WithMany("DocentVoorLesUitvoeringen")
                        .HasForeignKey("DocentId");

                    b.HasOne("HAN.ICDETool.Core.Entities.Locatie", "Locatie")
                        .WithMany("LesUitvoeringen")
                        .HasForeignKey("LocatieId");

                    b.Navigation("CourseWeekUitvoering");

                    b.Navigation("Docent");

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.OpleidingsProfiel", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.Opleiding", null)
                        .WithMany("OpleidingsProfielen")
                        .HasForeignKey("OpleidingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Rubric", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.BeroepsProduct", null)
                        .WithMany("Rubrics")
                        .HasForeignKey("BeroepsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.Leerdoel", "Leerdoel")
                        .WithMany("GekoppeldeRubrics")
                        .HasForeignKey("LeerdoelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Leerdoel");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.SchriftelijkeToets", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.CourseInrichting", null)
                        .WithMany("Toetsen")
                        .HasForeignKey("CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekInrichting", null)
                        .WithMany("SchriftelijkeToets")
                        .HasForeignKey("CourseWeekInrichtingId");

                    b.HasOne("HAN.ICDETool.Core.Entities.Leerdoel", "Leerdoel")
                        .WithMany("GekoppeldeToetsen")
                        .HasForeignKey("LeerdoelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Leerdoel");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.TentamenUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.BeroepsProduct", "BeroepsProduct")
                        .WithMany("TentamenUitvoeringen")
                        .HasForeignKey("BeroepsProductId");

                    b.HasOne("HAN.ICDETool.Core.Entities.CourseWeekUitvoering", "CourseWeekUitvoering")
                        .WithMany("Tentamen")
                        .HasForeignKey("CourseWeekUitvoeringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Core.Entities.Persoon", "Docent")
                        .WithMany("DocentVoorTentamenUitvoeringen")
                        .HasForeignKey("DocentId");

                    b.HasOne("HAN.ICDETool.Core.Entities.Locatie", "Locatie")
                        .WithMany("TentamenUitvoeringen")
                        .HasForeignKey("LocatieId");

                    b.HasOne("HAN.ICDETool.Core.Entities.SchriftelijkeToets", "SchriftelijkeToets")
                        .WithMany("TentamenUitvoeringen")
                        .HasForeignKey("SchriftelijkeToetsId");

                    b.Navigation("BeroepsProduct");

                    b.Navigation("CourseWeekUitvoering");

                    b.Navigation("Docent");

                    b.Navigation("Locatie");

                    b.Navigation("SchriftelijkeToets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Persoon", b =>
                {
                    b.HasOne("HAN.ICDETool.Core.Entities.Klas", "MentorVanKlas")
                        .WithOne("Mentor")
                        .HasForeignKey("HAN.ICDETool.Core.Entities.Persoon", "MentorVanKlasId");

                    b.HasOne("HAN.ICDETool.Core.Entities.CourseUitvoering", "VolgtCourse")
                        .WithMany("Studenten")
                        .HasForeignKey("VolgtCourseId");

                    b.HasOne("HAN.ICDETool.Core.Entities.OpleidingsProfiel", "VolgtProfiel")
                        .WithMany("GevolgdDoor")
                        .HasForeignKey("VolgtProfileId");

                    b.HasOne("HAN.ICDETool.Core.Entities.Klas", "ZitInKlas")
                        .WithMany("Studenten")
                        .HasForeignKey("ZitInKlasId");

                    b.Navigation("MentorVanKlas");

                    b.Navigation("VolgtCourse");

                    b.Navigation("VolgtProfiel");

                    b.Navigation("ZitInKlas");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.BeroepsProduct", b =>
                {
                    b.Navigation("Rubrics");

                    b.Navigation("TentamenUitvoeringen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseInrichting", b =>
                {
                    b.Navigation("BeroepsProducten");

                    b.Navigation("CourseUitvoeringen");

                    b.Navigation("Evls");

                    b.Navigation("Lessen");

                    b.Navigation("Planning");

                    b.Navigation("Toetsen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseUitvoering", b =>
                {
                    b.Navigation("Studenten");

                    b.Navigation("Weken");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekInrichting", b =>
                {
                    b.Navigation("BeroepsProduct");

                    b.Navigation("CourseWeekUitvoeringen");

                    b.Navigation("Lessen");

                    b.Navigation("SchriftelijkeToets");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekPlanning", b =>
                {
                    b.Navigation("Weken");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.CourseWeekUitvoering", b =>
                {
                    b.Navigation("Lessen");

                    b.Navigation("Tentamen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.EenheidVanLeeruitkomsten", b =>
                {
                    b.Navigation("Leeruitkomsten");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Klas", b =>
                {
                    b.Navigation("Mentor");

                    b.Navigation("Studenten");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Leerdoel", b =>
                {
                    b.Navigation("GekoppeldeLessen");

                    b.Navigation("GekoppeldeRubrics");

                    b.Navigation("GekoppeldeToetsen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Leeruitkomst", b =>
                {
                    b.Navigation("Leerdoelen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesInrichting", b =>
                {
                    b.Navigation("LesMateriaal");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.LesMateriaal", b =>
                {
                    b.Navigation("Inhoud");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Locatie", b =>
                {
                    b.Navigation("Adres");

                    b.Navigation("LesUitvoeringen");

                    b.Navigation("TentamenUitvoeringen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Opleiding", b =>
                {
                    b.Navigation("OpleidingsProfielen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.OpleidingsProfiel", b =>
                {
                    b.Navigation("GevolgdDoor");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Rubric", b =>
                {
                    b.Navigation("BeoordelingsCriteria");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.SchriftelijkeToets", b =>
                {
                    b.Navigation("TentamenUitvoeringen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.TentamenUitvoering", b =>
                {
                    b.Navigation("Beoordelingen");
                });

            modelBuilder.Entity("HAN.ICDETool.Core.Entities.Persoon", b =>
                {
                    b.Navigation("BeoordelingenGegeven");

                    b.Navigation("BeoordelingenOntvangen");

                    b.Navigation("DocentVoorLesUitvoeringen");

                    b.Navigation("DocentVoorTentamenUitvoeringen");
                });
#pragma warning restore 612, 618
        }
    }
}
