// <auto-generated />
using System;
using HAN.ICDETool.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAN.ICDETool.Infrastructure.Migrations
{
    [DbContext(typeof(ICDEContext))]
    partial class ICDEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAN.ICDETool.Domain.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Huisnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaatsnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toevoeging")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Beoordeling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TentamenUitvoeringId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TentamenUitvoeringId");

                    b.ToTable("Beoordeling");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.BeoordelingsCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RubricId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("BeoordelingsCriteria");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.BeroepsProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.Property<int>("TeBehalenStudiepunten")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.ToTable("BeroepsProduct");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseBibliotheek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("CourseBibliotheek");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseInrichting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseBibliotheekId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefintief")
                        .HasColumnType("bit");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanningId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseBibliotheekId");

                    b.HasIndex("PlanningId");

                    b.ToTable("CourseInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDatum")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.ToTable("CourseUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekInrichting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseWeekPlanningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseWeekPlanningId");

                    b.ToTable("CourseWeekInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("CourseWeekPlanning");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseUitvoeringId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseUitvoeringId");

                    b.ToTable("CourseWeekUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Docent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Docent");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.EenheidVanLeeruitkomsten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.ToTable("EenheidVanLeeruitkomstens");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Klas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("Klas");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Leerdoel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LeeruitkomstId")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeeruitkomstId");

                    b.ToTable("Leerdoel");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Leeruitkomst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EenheidVanLeeruitkomstenId")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EenheidVanLeeruitkomstenId");

                    b.ToTable("Leeruitkomst");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesInrichting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseInrichtingId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.Property<int?>("LeerdoelId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseInrichtingId");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.HasIndex("LeerdoelId");

                    b.ToTable("LesInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesMateriaal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LesInrichtingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LesInrichtingId");

                    b.ToTable("LesMateriaal");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesMateriaalLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LesMateriaalId")
                        .HasColumnType("int");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LesMateriaalId");

                    b.ToTable("LesMateriaalLine");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseWeekUitvoeringId")
                        .HasColumnType("int");

                    b.Property<int?>("DocentId")
                        .HasColumnType("int");

                    b.Property<int?>("LocatieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseWeekUitvoeringId");

                    b.HasIndex("DocentId");

                    b.HasIndex("LocatieId");

                    b.ToTable("LesUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Locatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresId")
                        .HasColumnType("int");

                    b.Property<int>("LocatieType")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Locatie");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Opleiding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Opleiding");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.OpleidingsProfiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpleidingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpleidingId");

                    b.ToTable("OpleidingsProfiel");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Rubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeroepsProductId")
                        .HasColumnType("int");

                    b.Property<int>("KnockoutThreshold")
                        .HasColumnType("int");

                    b.Property<int?>("LeerdoelId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoldoendeThreshold")
                        .HasColumnType("int");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeroepsProductId");

                    b.HasIndex("LeerdoelId");

                    b.ToTable("Rubric");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.SchriftelijkeToets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseWeekInrichtingId")
                        .HasColumnType("int");

                    b.Property<int?>("LeerdoelId")
                        .HasColumnType("int");

                    b.Property<int>("TeBehalenStudiepunten")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseWeekInrichtingId");

                    b.HasIndex("LeerdoelId");

                    b.ToTable("SchriftelijkeToets");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlasId")
                        .HasColumnType("int");

                    b.Property<int>("VolgCourseId")
                        .HasColumnType("int");

                    b.Property<int>("VolgtProfielId")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasId");

                    b.HasIndex("VolgCourseId");

                    b.HasIndex("VolgtProfielId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.TentamenUitvoering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeroepsProductId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseWeekUitvoeringId")
                        .HasColumnType("int");

                    b.Property<int?>("DocentId")
                        .HasColumnType("int");

                    b.Property<int?>("LocatieId")
                        .HasColumnType("int");

                    b.Property<int?>("SchriftelijkeToetsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeroepsProductId");

                    b.HasIndex("CourseWeekUitvoeringId");

                    b.HasIndex("DocentId");

                    b.HasIndex("LocatieId");

                    b.HasIndex("SchriftelijkeToetsId");

                    b.ToTable("TentamenUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Beoordeling", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Docent", "BeoordeeldDoor")
                        .WithMany()
                        .HasForeignKey("DocentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Domain.Student", "BeoordelingVoor")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Domain.TentamenUitvoering", "TentamenUitvoering")
                        .WithMany()
                        .HasForeignKey("TentamenUitvoeringId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BeoordeeldDoor");

                    b.Navigation("BeoordelingVoor");

                    b.Navigation("TentamenUitvoering");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.BeoordelingsCriteria", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Rubric", null)
                        .WithMany("BeoordelingsCriteria")
                        .HasForeignKey("RubricId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.BeroepsProduct", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseWeekInrichting", null)
                        .WithMany("BeroepsProduct")
                        .HasForeignKey("CourseWeekInrichtingId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseInrichting", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseBibliotheek", null)
                        .WithMany("Courses")
                        .HasForeignKey("CourseBibliotheekId");

                    b.HasOne("HAN.ICDETool.Domain.CourseWeekPlanning", "Planning")
                        .WithMany()
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseInrichting", "CourseInrichting")
                        .WithMany()
                        .HasForeignKey("CourseInrichtingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseInrichting");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekInrichting", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseWeekPlanning", null)
                        .WithMany("Weken")
                        .HasForeignKey("CourseWeekPlanningId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseUitvoering", null)
                        .WithMany("Weken")
                        .HasForeignKey("CourseUitvoeringId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.EenheidVanLeeruitkomsten", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseInrichting", null)
                        .WithMany("Evls")
                        .HasForeignKey("CourseInrichtingId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Klas", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Docent", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Leerdoel", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Leeruitkomst", null)
                        .WithMany("Leerdoelen")
                        .HasForeignKey("LeeruitkomstId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Leeruitkomst", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.EenheidVanLeeruitkomsten", null)
                        .WithMany("Leeruitkomsten")
                        .HasForeignKey("EenheidVanLeeruitkomstenId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesInrichting", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseInrichting", null)
                        .WithMany("Lessen")
                        .HasForeignKey("CourseInrichtingId");

                    b.HasOne("HAN.ICDETool.Domain.CourseWeekInrichting", null)
                        .WithMany("Lessen")
                        .HasForeignKey("CourseWeekInrichtingId");

                    b.HasOne("HAN.ICDETool.Domain.Leerdoel", null)
                        .WithMany("GekoppeldeLessen")
                        .HasForeignKey("LeerdoelId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesMateriaal", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.LesInrichting", null)
                        .WithMany("LesMateriaal")
                        .HasForeignKey("LesInrichtingId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesMateriaalLine", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.LesMateriaal", null)
                        .WithMany("Inhoud")
                        .HasForeignKey("LesMateriaalId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseWeekUitvoering", null)
                        .WithMany("Lessen")
                        .HasForeignKey("CourseWeekUitvoeringId");

                    b.HasOne("HAN.ICDETool.Domain.Docent", "Docent")
                        .WithMany()
                        .HasForeignKey("DocentId");

                    b.HasOne("HAN.ICDETool.Domain.Locatie", "Locatie")
                        .WithMany()
                        .HasForeignKey("LocatieId");

                    b.Navigation("Docent");

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Locatie", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresId");

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.OpleidingsProfiel", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Opleiding", null)
                        .WithMany("OpleidingsProfielen")
                        .HasForeignKey("OpleidingId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Rubric", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.BeroepsProduct", null)
                        .WithMany("Rubrics")
                        .HasForeignKey("BeroepsProductId");

                    b.HasOne("HAN.ICDETool.Domain.Leerdoel", null)
                        .WithMany("GekoppeldeRubrics")
                        .HasForeignKey("LeerdoelId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.SchriftelijkeToets", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.CourseWeekInrichting", null)
                        .WithMany("SchriftelijkeToets")
                        .HasForeignKey("CourseWeekInrichtingId");

                    b.HasOne("HAN.ICDETool.Domain.Leerdoel", null)
                        .WithMany("GekoppeldeToetsen")
                        .HasForeignKey("LeerdoelId");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Student", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.Klas", null)
                        .WithMany("Studenten")
                        .HasForeignKey("KlasId");

                    b.HasOne("HAN.ICDETool.Domain.CourseUitvoering", "VolgCourse")
                        .WithMany()
                        .HasForeignKey("VolgCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAN.ICDETool.Domain.OpleidingsProfiel", "VolgtProfiel")
                        .WithMany()
                        .HasForeignKey("VolgtProfielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VolgCourse");

                    b.Navigation("VolgtProfiel");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.TentamenUitvoering", b =>
                {
                    b.HasOne("HAN.ICDETool.Domain.BeroepsProduct", "BeroepsProduct")
                        .WithMany()
                        .HasForeignKey("BeroepsProductId");

                    b.HasOne("HAN.ICDETool.Domain.CourseWeekUitvoering", null)
                        .WithMany("Tentamen")
                        .HasForeignKey("CourseWeekUitvoeringId");

                    b.HasOne("HAN.ICDETool.Domain.Docent", "Docent")
                        .WithMany()
                        .HasForeignKey("DocentId");

                    b.HasOne("HAN.ICDETool.Domain.Locatie", "Locatie")
                        .WithMany()
                        .HasForeignKey("LocatieId");

                    b.HasOne("HAN.ICDETool.Domain.SchriftelijkeToets", "SchriftelijkeToets")
                        .WithMany()
                        .HasForeignKey("SchriftelijkeToetsId");

                    b.Navigation("BeroepsProduct");

                    b.Navigation("Docent");

                    b.Navigation("Locatie");

                    b.Navigation("SchriftelijkeToets");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.BeroepsProduct", b =>
                {
                    b.Navigation("Rubrics");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseBibliotheek", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseInrichting", b =>
                {
                    b.Navigation("Evls");

                    b.Navigation("Lessen");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseUitvoering", b =>
                {
                    b.Navigation("Weken");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekInrichting", b =>
                {
                    b.Navigation("BeroepsProduct");

                    b.Navigation("Lessen");

                    b.Navigation("SchriftelijkeToets");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekPlanning", b =>
                {
                    b.Navigation("Weken");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.CourseWeekUitvoering", b =>
                {
                    b.Navigation("Lessen");

                    b.Navigation("Tentamen");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.EenheidVanLeeruitkomsten", b =>
                {
                    b.Navigation("Leeruitkomsten");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Klas", b =>
                {
                    b.Navigation("Studenten");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Leerdoel", b =>
                {
                    b.Navigation("GekoppeldeLessen");

                    b.Navigation("GekoppeldeRubrics");

                    b.Navigation("GekoppeldeToetsen");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Leeruitkomst", b =>
                {
                    b.Navigation("Leerdoelen");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesInrichting", b =>
                {
                    b.Navigation("LesMateriaal");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.LesMateriaal", b =>
                {
                    b.Navigation("Inhoud");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Opleiding", b =>
                {
                    b.Navigation("OpleidingsProfielen");
                });

            modelBuilder.Entity("HAN.ICDETool.Domain.Rubric", b =>
                {
                    b.Navigation("BeoordelingsCriteria");
                });
#pragma warning restore 612, 618
        }
    }
}
